DataDir =  "/root/CoverageControl_ws/data/pure_coverage/" # Absolute location

GPUs =  [4, 5]

[ModelConfig]
UseCommMaps = True


[GNNBackBone]
InputDim = 7
NumHops = 3
NumLayers = 4
LatentSize = 64
OutputDim = 2

[GNNTraining]
LearningRate = 0.001
WeightDecay = 0.0001
BatchSize = 10
NumEpochs = 50

[CNNBackBone]
InputDim = 4
OutputDim = 7
NumLayers = 2
LatentSize = 8
KernelSize = 3
ImageSize = 32

[CNNTraining]
LearningRate = 0.001
WeightDecay = 0.0001
BatchSize = 10
NumEpochs = 50

