name: CoverageControl
channels:
  - defaults
  - pytorch
  - pypi
dependencies:
  - pip
  - numpy
  - matplotlib
  - seaborn
  - pytz
  - pyyaml
  - shapely
  - pip:
    - OSMPythonTools
    - geojson
    - geopy
    - geographiclib
