name: docker-deploy
on:
  workflow_dispatch:
  release:
    types: [published]

env:
  FORCE_COLOR: 3

jobs:
  docker-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: 'CI docker base'
        uses: ./.github/docker-base-action
        with:
          base_tag: pytorch2.2.2-cuda12.2.2-ros2humble
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: cleanup
        run: docker system prune -a -f
      - name: 'CI docker base'
        uses: ./.github/docker-base-action
        with:
          base_tag: pytorch2.2.2-ros2humble
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: cleanup
        run: docker system prune -a -f
      - name: 'CI docker base'
        uses: ./.github/docker-base-action
        with:
          base_tag: pytorch2.2.2-cuda12.2.2
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: cleanup
        run: docker system prune -a -f
      - name: 'CI docker base'
        uses: ./.github/docker-base-action
        with:
          base_tag: pytorch2.2.2
          github_token: ${{ secrets.GITHUB_TOKEN }}
