on:
  release:
    types: [published]
  push:
    paths:
      - 'doc/**'
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Action Doxygen and GitHub Pages
        id: ghaction
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@v2.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          doxyfile-path: doc/Doxyfile
          html-output-folder: doc/html
          branch: gh-pages
